### ISSUE TITLE
[DMF] GDPR concerns on 'Information about the Person'

### ISSUE THREAD

**Issue by jeborsel** [european-commission-europass/Europass-Learning-Model#10]
**Describe the organisation you represent**
Open Recognition Alliance , issue filed as part of a collective review process during ePIC2019 https://epic.openrecognition.org/

**Specify the *nature* of your comment**
Choose *labels* from the right hand side to categorise your comment. Feedback types include:
* a question about the data model or a specific content item

**Free text comment**
For the person about which claims are made and who owns the credential, there is data such as name, date of birth, student ID identifiers that are processed. The GDPR provides guidelines and
limitations on this. How will explicit consent be managed ?

**Comment by anthonycamilleri** [comment]
Explicit consent is dealt with by the organisation that issues the credential. EDCI-Issuer has added a specific consent dialog for institutions to confirm they have received this consen as a resolution of this issue.
