### ISSUE TITLE
[DMF] Achievement object doesn't seem to capture informal learning at the moment

### ISSUE THREAD

**Issue by jeborsel** [european-commission-europass/Europass-Learning-Model#12]
**Describe the organisation you represent**
Open Recognition Alliance , issue filed as part of a collective review process during ePIC2019 https://epic.openrecognition.org/

**Specify the *nature* of your comment**
* a suggested change or adjustment 

**Free text comment**
An achievement is described as the outcome of a learning process and/or assessment in formal, non-formal or informal settings. 
So informal learning could be captured in this via e.g. the use of Open Badges. But in the types of achievement that are further worked out in the model only those that fit more formal (and non-formal) learning or captured and no types that fit the informal setting.

**Comment by anthonycamilleri** [comment]
Informal learning is captured through the 'activity' field rather than the 'achievement' field.
