### ISSUE TITLE
[DMF] Why is the EU data model in American English? 

### ISSUE THREAD

**Issue by SebastianSK** [european-commission-europass/Europass-Learning-Model#22]
Sebastian Sklarß from ]init[ AG 

I would like to raise a general question on the whole data model.

Why is American English used in contrast to British English?
Examples: Organization instead of Organisation

Reasoning:
Other EU driven standards and initiatives (even when reusing W3C)  like DIGIT Core Location[1], DCAT-AP [2] vocabulary or the former Share PSI [3] used British English when introducing new concepts.

[1] https://www.w3.org/ns/locn
[2] https://github.com/SEMICeu/DCAT-AP
[3] https://www.w3.org/2013/share-psi/

- I am currently working on a data exchange standard in education area for the implementation of the online access act (OZG) and therefore I evaluate EDCI for potential reuse

**Comment by anthonycamilleri** [comment]
@IldikoMazar we still have a couple of zs under the 'registration' property.

**Comment by IldikoMazar** [comment]
Organisation spelling has been corrected to British English in "Registration" property of "Organisation" class - other US spellings were eliminated at earlier stages.
