### ISSUE TITLE
[DMF] Proper use of lang-tag in examples

### ISSUE THREAD

**Issue by SebastianSK** [european-commission-europass/Europass-Learning-Model#23]
**Describe the organisation you represent**
]init[ AG  

**Specify the *nature* of your comment**
Choose *labels* from the right hand side to categorise your comment. Feedback types include:
comment on markup in the XML examples

The examples (e.g. in https://github.com/european-commission-europass/Europass-Learning-Model/blob/master/edci_presentation.xml)  do not yet demonstrate proper use of the lang-tag when refering to alternative labels for University names 

I expected to see something like the following:
```
<altLabel lang="en">Catholic University of Leuven</altLabel>
<altLabel lang="de">Katholische Universität Löwen</altLabel>
<altLabel lang="nl">Katholieke Universiteit te Leuven</altLabel>
```

Instead it is stated:
`<altLabel lang="en">Katholieke Universiteit Leuven</altLabel>`

**Comment by anthonycamilleri** [comment]
Solved in release 1.0
