### ISSUE TITLE
[DMF] birthName of a learner missing 

### ISSUE THREAD

**Issue by SebastianSK** [european-commission-europass/Europass-Learning-Model#24]
**Describe the organisation you represent**
]init[ AG

**Specify the *nature* of your comment**
a suggested adjustment

**Free text comment**
The name of birth of a learner might be important for the "identify" use case in Member States like Germany where a national ID does not exist.

Example: Eva Mustermann, geb. Gabler
https://upload.wikimedia.org/wikipedia/commons/3/37/Mustermann_Reisepass_2017.jpg

additional note:
The november 2019 version 1.5 of EMREX/ELMO added the name of birth of a person 
https://github.com/emrex-eu/elmo-schemas/releases/tag/v1.5.0

In case an ongoing alignement with ELMO is intended this is another argument for adding the property birthName

I suggest 
1. to add this property temporarly at EDCI level but also 
2. to raise this issue together with "family names" and "given names" at W3C verifiable credential level, https://github.com/w3c/vc-data-model/issues 
as currently only "name" is supported in the candidate recommendation
https://www.w3.org/TR/2019/REC-vc-data-model-20191119/#example-15-a-simple-credential 

`"credentialSubject": {
    "id": "did:example:abcdef1234567",
    "name": "Jane Doe"
  },`

**Comment by anthonycamilleri** [comment]
@IldikoMazar we should Align here with SEMIC Vocabularies available here: https://joinup.ec.europa.eu/sites/default/files/distribution/2013-10/Core_Vocabularies-Business_Location_Person-Specification-v1.00.pdf

Specifically we should add:
- patronymicname
- birth name

**Comment by IldikoMazar** [comment]
Aligned Europass vocabulary with SEMIC, and added "Birth Name" and "Patronymic Name" to our data model
