### ISSUE TITLE
[DMF] own Europass media types instead of OPOCE file type?

### ISSUE THREAD

**Issue by SebastianSK** [european-commission-europass/Europass-Learning-Model#25]
**Describe the organisation you represent**
]init[ 

**Specify the *nature* of your comment**
* a question about the data model or a specific content item

**Free text comment**
Why was there the need to create an own Europass vocabulary for media types?

Isn't using 
`http://publications.europa.eu/resource/authority/file-type` 
with a short list of permitted values like
```
http://publications.europa.eu/resource/authority/file-type/PNG
http://publications.europa.eu/resource/authority/file-type/PDF
```
and the additional feature to distinguish PDF and PDFA 
`http://publications.europa.eu/resource/authority/file-type/PDFA1A `
a better approach?

**Comment by anthonycamilleri** [comment]
Agreed, and moving to these filetypes.
