### ISSUE TITLE
non-functioning links in EDCI_model.xlsx

### ISSUE THREAD

**Issue by JochenEhrenreich** [european-commission-europass/Europass-Learning-Model#3]
I am a researcher at DHBW Heilbronn (Baden Wuerttemberg Cooperative State University Heilbronn, Germany).

Most of the links do not seem to work in the excel list [EDCI_model.xlsx]( https://github.com/european-commission-europass/EDCI-Data-Model/blob/master/ECDI_model.xlsx?raw=true)

example: http://data.europa.eu/europass/codeList/assessmentTypes

**Comment by anthonycamilleri** [comment]
The namespaces indicated in the Excel sheet are not final. Dereferencability of concepts will be implemented by launch in May 2020.

**Comment by anthonycamilleri** [comment]
Addressed 1.0
