### ISSUE TITLE
[DMF] Adaption of the model for intersex people

### ISSUE THREAD

**Issue by nachtjasmin** [european-commission-europass/Europass-Learning-Model#30]
**Describe the organisation you represent**
The [GWDG](https://www.gwdg.de), an organization related to the University of Göttingen and the Max-Planck institute. Currently working together with other universities to implement a platform for international student mobility.

**Specify the *nature* of your comment**
Choose *labels* from the right hand side to categorise your comment. Feedback types include:

* a suggested change or adjustment 

**Free text comment**
The [edci_mdr_humansex.xsd](https://github.com/european-commission-europass/Europass-Learning-Model/blob/master/XSD/imported/edci_mdr_humansex.xsd) contains two possible values for the human sex. However, in reality intersex people neither fit into these models.

As a solution to this, we in Germany have four different possible values for the *Personenstand* (vital record): male, female, diverse, empty value.

In order to align the data model with the national conventions, I suppose two different changes:

1. Extend the `edci_mdr_humansex.xsd` enumeration by two more values.
2. Remove all references to the human sex.

Personally I'd like to see the second change, as it would make the data model also more friendly to transgender people. Yes, this is very subjective, but in my opinion there's absolutely no need for the sex/gender in the data model. The combination from name and ID should provide enough relevant information.

**Comment by anthonycamilleri** [comment]
We rely on SEMIC vocabularies which are centralised at EU level for our concepts of 'sex' and 'gender'. I would recommend you raise this issue for their vocabularies. You can do so here: https://github.com/SEMICeu/Core-Person-Vocabulary
