### ISSUE TITLE
[DMF] Restrictions on EuropassCredentialIssuer

### ISSUE THREAD

**Issue by jeborsel** [european-commission-europass/Europass-Learning-Model#9]
**Describe the organisation you represent**
Open Recognition Alliance , issue filed as part of a collective review process during ePIC2019 https://epic.openrecognition.org/

**Specify the *nature* of your comment**
* a question about the data model or a specific content item

**Free text comment**
The restricted range of issuers of EuropassCredential are organisations , for verifiable credentials this can be any entity (such as persons, organizations, or devices)  , are these also accepted in the EDCI?
And to what extent is the 'has accredition' optional for issuers?

**Comment by anthonycamilleri** [comment]
hasaccreditatoin is optional. Due to limitations of signature with eSeal, the range remains organisations.
